# Generated by Django 3.2.9 on 2021-11-24 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='phone',
            new_name='phone_num',
        ),
    ]
