
PLAYER_X_SYMBOL = 'X'
PLAYER_O_SYMBOL = 'O'
STARTING_PLAYER_SYMBOL = PLAYER_X_SYMBOL
BOARD_EMPTY_SPACE_SYMBOL = ' '
ROW_NUM = COL_NUM = 3

DEFAULT_WELCOME_MSG = "Welcome to TIC TAC TOE!"
DEFAULT_GAME_TITLE = "TIC TAC TOE"
DEFAULT_DRAW_MSG = "Draw!"
INVALID_PLACEMENT_MSG = "Board isn't empty at this location, please choose another!";
