# Generated by Django 3.2.9 on 2021-11-30 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country'},
        ),
    ]
